### PR TITLE
Katie/continuing work

### PR DESCRIPTION
**Pull request by kavedder**
[Review on Reviewable](https://reviewable.io/reviews/socrata/arcs/1)

### CODE REVIEW

**Comment by rlvoyer** [comment]
Review status: 0 of 14 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

<sup>**[arcs/calc_iaa.py, line 10 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNuKWRP8KkltIVWx2g)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/calc_iaa.py#L10)):</sup>
I'm inclined to use Pandas here rather than writing this logic explicitly. My sense is that it makes the code less error-prone, more concise, and easier to maintain. Thoughts?

---

<sup>**[arcs/calc_iaa.py, line 31 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNuxyJK4qrKatv5DIZ)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/calc_iaa.py#L31)):</sup>
Use Pandas, as suggested above?

---

<sup>**[arcs/collection.py, line 130 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNw7iHDvSTEsGk_tfU)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/collection.py#L130)):</sup>
Why is this gross?

---

<sup>**[arcs/collection.py, line 213 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNwGvbmQiTIvg4BB3s)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/collection.py#L213)):</sup>
Should we do this at the module-level?

---

<sup>**[arcs/collection.py, line 295 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNwrC2MgFHux3Cr6fa)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/collection.py#L295)):</sup>
Remove?

---

<sup>**[arcs/download_crowdflower.py, line 36 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNxRKoCZF8cGaNvm1w)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/download_crowdflower.py#L36)):</sup>
Remove?

---

<sup>**[arcs/download_crowdflower.py, line 37 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNxSTmP0-XCuM50ajQ)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/download_crowdflower.py#L37)):</sup>
Remove?

---

<sup>**[arcs/download_crowdflower.py, line 55 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNxkoR1m2lMonqymth)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/download_crowdflower.py#L55)):</sup>
Remove?

---

<sup>**[arcs/download_crowdflower.py, line 63 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNxpDmYBPO-JT9Ljuf)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/download_crowdflower.py#L63)):</sup>
Maybe we should report these in the output of this script?

---

<sup>**[arcs/measure_ndcg.py, line 12 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwO-ltI4MxXNrNYuvj8)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/measure_ndcg.py#L12)):</sup>
Any reason not to make this a top-level function? It'll make it more testable.

---

<sup>**[arcs/measure_ndcg.py, line 15 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNz45knTrhLluVNxen)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/measure_ndcg.py#L15)):</sup>
I'm inclined to use the variant described here: https://en.wikipedia.org/wiki/Discounted_cumulative_gain#Discounted_Cumulative_Gain, since (according to Wikipedia) it's the industry standard and it simplifies this function somewhat since it can be done using the built-in sum:

```python
def dcg(judgments):
    return sum([(2**j - 1) / log(i + 1, 2) for (i, j) in enumerate(judgments)])
```

---

<sup>**[arcs/measure_ndcg.py, line 31 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwO-tS_rjQf2A9De-uH)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/measure_ndcg.py#L31)):</sup>
We should (at some point) move this out into a unit test.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/socrata/arcs/1)

**Comment by kavedder** [comment]
Review status: 0 of 15 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

<sup>**[arcs/calc_iaa.py, line 10 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNuKWRP8KkltIVWx2g)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/calc_iaa.py#L10)):</sup>
Agreed. 

---

<sup>**[arcs/calc_iaa.py, line 31 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNuxyJK4qrKatv5DIZ)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/calc_iaa.py#L31)):</sup>
Ditto

---

<sup>**[arcs/collection.py, line 130 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNw7iHDvSTEsGk_tfU)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/collection.py#L130)):</sup>
Oh, I really don't like using a list comprehension that doesn't output anything, but I suppose a little part of me finds it satisfying, so I do it.

---

<sup>**[arcs/collection.py, line 213 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNwGvbmQiTIvg4BB3s)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/collection.py#L213)):</sup>
probably.

---

<sup>**[arcs/collection.py, line 295 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNwrC2MgFHux3Cr6fa)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/collection.py#L295)):</sup>
Sure. Though more logging doesn't ever hurt.

---

<sup>**[arcs/download_crowdflower.py, line 36 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNxRKoCZF8cGaNvm1w)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/download_crowdflower.py#L36)):</sup>
certainly.

---

<sup>**[arcs/download_crowdflower.py, line 37 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNxSTmP0-XCuM50ajQ)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/download_crowdflower.py#L37)):</sup>
indubitably.

---

<sup>**[arcs/download_crowdflower.py, line 55 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNxkoR1m2lMonqymth)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/download_crowdflower.py#L55)):</sup>
Instead of commenting out one line and uncommenting another, this should be a flag (like -c --cache to load from json)

---

<sup>**[arcs/download_crowdflower.py, line 63 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNxpDmYBPO-JT9Ljuf)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/download_crowdflower.py#L63)):</sup>
This, and throwing away the 1-values at the bottom here. This whole thing ought to also perhaps be in a function named for what it does (get the ndcg for each domain, query)

---

<sup>**[arcs/measure_ndcg.py, line 15 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNz45knTrhLluVNxen)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/measure_ndcg.py#L15)):</sup>
That...doesn't quite work, does it? At i = 1, you're dividing by log(1) = 0. Ah, I see, the mathematical notation is 1-indexed. I think if we just change it to 
```python
sum([(2**j - 1) / log(i + 2, 2) for (i, j) in enumerate(judgments)])
```
 that'll work. I'm okay with using that version. I didn't notice that section I suppose :-D

---

<sup>**[arcs/measure_ndcg.py, line 31 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwO-tS_rjQf2A9De-uH)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/measure_ndcg.py#L31)):</sup>
We should (at some point) have unit tests :-)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/socrata/arcs/1)

**Comment by rlvoyer** [comment]
<sup>**[arcs/collection.py, line 130 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNw7iHDvSTEsGk_tfU)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/collection.py#L130)):</sup>
Oh, the comment applies to this?

```python
    [dom_counts[d].add(q) for d, q, rl in filtered]
```

If so, I agree with you.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/socrata/arcs/1)

**Comment by rlvoyer** [comment]
<sup>**[arcs/collection.py, line 295 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNwrC2MgFHux3Cr6fa)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/collection.py#L295)):</sup>
No, but it can be confusing. I'm not clear what prefacing `args` w/ "Namespace:" is telling us. Maybe it should be "Parameters:"?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/socrata/arcs/1)

**Comment by rlvoyer** [comment]
<sup>**[arcs/measure_ndcg.py, line 15 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNz45knTrhLluVNxen)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/measure_ndcg.py#L15)):</sup>
One additional thought. We might actually want to take two iterables as input. One for the positions of each judged result, and the other for the actual judgments. This seems more precise than simply using enumerate, since it's possible that a particular a result will be filtered out (for being in a foreign language, for example).

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/socrata/arcs/1)

**Comment by kavedder** [comment]
Review status: 0 of 15 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

<sup>**[arcs/measure_ndcg.py, line 15 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNz45knTrhLluVNxen)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/measure_ndcg.py#L15)):</sup>
How about an indexed dict? 
```python
{1:2, 2:3, 3:4}
```
that's what I ended up with.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/socrata/arcs/1)

**Comment by rlvoyer** [comment]
<sup>**[arcs/measure_ndcg.py, line 15 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNz45knTrhLluVNxen)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/measure_ndcg.py#L15)):</sup>
The indexed dict approach is totally reasonable, but I'm partial to taking simple array-like iterables for integration w/ pandas and numpy. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/socrata/arcs/1)

**Comment by kavedder** [comment]
Review status: 0 of 15 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

<sup>**[arcs/collection.py, line 130 \[r3\]](https://reviewable.io:443/reviews/socrata/arcs/1#-JwNw7iHDvSTEsGk_tfU)** ([raw file](https://github.com/socrata/arcs/blob/5d63102372af921981f19f776c307533457afdf2/arcs/collection.py#L130)):</sup>
left in for now

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/socrata/arcs/1)

**Pull request merged**
